parameters:
    environments:
        'Web' : 'web'
        'Merge' : 'merge'
        'FAT' : 'fat'
        'Production' : 'production'
        'Training' : 'trainning'
        'Marketing' : 'marketing'
    teams:
        'Unsure' : 'Unsure'
        'Client Services' : 'Client Services Development Team'
        'Business' : 'Business Development Team'
        'CIC' : 'CIC Team'
        'Claims' : 'Claims Development Team'
        'Correspondence' : 'Correspondence Development Team'
        'Sales' : 'Sales Development Team'
        'Digital' : 'Digital Client Channel Development Team'
        'Innovation Banking' : 'Innov - Accounts and Banking Development'
        'Oracle Architect' : 'Innov - Tia Solutions Arc'
        'PHP Architect' : 'Innov - PHP Solutions Arc'
        'Integration' : 'Innov - Integration'
        'MIS' : 'MIS'
        'Maintenance' : 'Tia Maintenance'
        'Actuarial Motor' : 'Actuarial Motor'
        'Actuarial Non Motor' : 'Actuarial Non Motor'
        'eLingo' : 'CIC - eLingo'
    issue_type:
        'Bug-Fix' : 'bug-fix'
        'New Feature' : 'New Feature'