_homepage:
    path: '/'
    defaults: { _controller: 'AppBundle:Default:index' }

_add_object:
    path: '/object/add'
    defaults: { _controller: 'AppBundle:Default:addMediaObject' }

_view_object:
    path: '/object/view/{id}'
    defaults: { _controller: 'AppBundle:Default:viewMediaObject' }

_search_object:
    path: '/object/search/{searchterm}'
    defaults: { _controller: 'AppBundle:Default:search' }