_homepage:
    path: '/'
    defaults: { _controller: 'AppBundle:Default:index' }

_add_media_object:
    path: '/add-media-object'
    defaults: { _controller: 'AppBundle:Default:addMediaObject' }

_media_add_success:
    path: '/add-success'
    defaults: { _controller: 'AppBundle:Default:succussfullyAddedMedia' }