fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

_homepage:
    path: '/'
    defaults: { _controller: 'AppBundle:Default:index' }
    options:
        expose: true

_add_object:
    path: '/object/add'
    defaults: { _controller: 'AppBundle:Default:addObject' }

_view_object:
    path: '/object/view/{id}'
    defaults: { _controller: 'AppBundle:Default:viewObject' }
    options:
        expose: true

_search_object:
    path: '/object/search/{searchTerm}'
    defaults: { _controller: 'AppBundle:Default:search' }
    options:
        expose: true

_delete_object:
    path: '/object/delete/{id}'
    defaults: { _controller: 'AppBundle:Default:deleteObject'}
    options:
        expose: true

_edit_object:
    path: '/object/edit/{id}'
    defaults: { _controller: 'AppBundle:Default:editObject' }

_login:
    path: 'login'
    defaults: { _controller: 'AppBundle:Security:login' }

logout:
    path: '/logout'

_media_item:
    path: '/media/{mediaName}'

_jira_get_story:
    path: '/jira/fetch/{story}'
    defaults: { _controller: 'AppBundle:Jira:fetchStoryDetails', story : "" }
    options:
        expose: true