# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    media.object.form:
        class: AppBundle\Form\MediaObjectType
        arguments: ['@service_container', '@security.token_storage']
        tags:
            - { name: form.type }

    form_authenticator:
        class: AppBundle\Security\FormAuthenticator
        arguments: ['@router']

    query.manager:
        class: AppBundle\Entity\Queries\Manager
        arguments: ['@doctrine.orm.entity_manager']

    string.replace.twig_extension:
        class: AppBundle\Twig\StringReplaceExtension
        public: false
        tags:
            - { name: twig.extension }
